---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-{{ .Values.username }}-access-right
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io","extensions", "apps"]
  resources: ["deployments", "replicasets","secrets","ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace }}-{{ .Values.username }}-access-right-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: User
  name: momo-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Values.namespace }}-{{ .Values.username }}-access-right
  apiGroup: rbac.authorization.k8s.io