---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"        
        volumeMounts:
        - name: prometheus-server-conf
          mountPath: /etc/prometheus
        command:
        - "/bin/prometheus"
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
      volumes:
      - name: prometheus-server-conf
        configMap:
          defaultMode: 420
          name: prometheus-server-conf
      nodeSelector:
        topology.kubernetes.io/zone: eu-central-1b