---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: momo-grafana-ingress
spec:
  ingressClassName: "nginx"
  tls:
  - secretName: sudouser-net
    hosts:
      - momo-grafana.sudouser.net
  rules:
  - host: momo-grafana.sudouser.net
    http: 
      paths: 
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: grafana-service
            port: 
              number: 80