apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteMany
  claimRef:
    name: grafana-pvc
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-02541591c014fce33
  capacity:
    storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: grafana-pv
  resources:
    requests:
      storage: 1Gi